[supervisord]
nodaemon=true
logfile=/dev/stdout
logfile_maxbytes=0

[program:nginx]
command=nginx -g "daemon off;"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
autorestart=true

[program:bridge]
command=python3 /app/ws_bridge.py
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
autorestart=true

[program:bridge-tcp-sync]
command=python3 /app/ws_bridge_tcp.py
environment=SYNC_ENABLED="1",TCP_SERVER_HOST="tcp-sync.exam.lan",TCP_SERVER_PORT="9001",BRIDGE_PORT="8082"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
autorestart=true

[program:bridge-tcp-nosync]
command=python3 /app/ws_bridge_tcp.py
environment=SYNC_ENABLED="0",TCP_SERVER_HOST="tcp-nosync.exam.lan",TCP_SERVER_PORT="9001",BRIDGE_PORT="8083"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
autorestart=true
